### ISSUE TITLE
Missing minbar_sources.fits file

### ISSUE THREAD

**Issue by yveskini** [outs1der/minbar#26]
In order for the `mb.create_distance_correction()` method to work correctly as demonstrated in the `Example Usage`, the file `minbar_sources.fits` is essential. I'd like to suggest a slight modification to the Getting Started section as follows:

Change this:

"Copy the MINBAR table files `minbar.txt` and `minbar-obs.txt ` into the data directory, or softlink to the locations"

To something like this :

"Copy the MINBAR table files `minbar.txt`, `minbar-obs.txt`, and `minbar_sources.fits` (rename the downloaded `minbar_sources_vXX.fit` to `minbar_sources.fits`) into the data directory, or softlink them to the respective locations."

This updated instruction should help ensure that users have all the necessary files in place for the functionality of `mb.create_distance_correction()`.

**Comment by outs1der** [comment]
Thanks – have updated the `README.md` as suggested
